# Generated by Django 5.1.3 on 2024-11-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('related_roadmap', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('resource_type', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.career')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_to_complete', models.DurationField()),
                ('skills_required', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.career')),
            ],
        ),
    ]
